export const IPC_EVENTS = {
  CHAT_STREAM: "chat:stream",
  CHAT_ABORT: "chat:abort",
  CHAT_CHUNK: "chat:chunk",
  CHAT_DONE: "chat:done",
  CHAT_ERROR: "chat:error",
  CHAT_REASONING_CHUNK: "chat:reasoning_chunk",
  CHAT_TOOL_CALL_START: "chat:tool_call_start",
  CHAT_TOOL_CALL_END: "chat:tool_call_end",
  CHAT_ASSISTANT_MESSAGE: "chat:assistant-message",
  CHAT_TOOL_MESSAGE_PERSISTED: "chat:tool-message-persisted",
  CHAT_STREAM_RETRY: "chat:stream-retry",
  CHAT_MODE_STATE_CHANGED: "chat:mode-state-changed",
  PLAN_ARTIFACT_CREATED: "plan:artifact-created",
  PLAN_ARTIFACT_INVALIDATED: "plan:artifact-invalidated",
  PLAN_EXECUTION_STARTED: "plan:execution-started",
  PLAN_EXECUTION_ERROR: "plan:execution-error",
  SPEECH_TRANSCRIBE: "speech:transcribe",
  PROJECT_CHANGED: "project:changed",
  SETTINGS_CHANGED: "settings:changed",
  SKILLS_CHANGED: "skills:changed",
  MCP_CHANGED: "mcp:changed",
  TASK_CHANGED: "task:changed",
  CONVERSATIONS_CHANGED: "conversations:changed",
  AGENTS_LIST: "agents:list",
  AGENTS_CHANGED: "agents:changed",
  COMPACT_RUN: "compact:run",
} as const;
